<?php

/**
 * @file Secure Permissions Data
 * Module file for secure permissions in code.
 */

/**
 * Define site roles in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @return
 *   An array defining all the roles for the site.
 */
function pinnakl_secure_permissions_roles() {
  return array(
    'anonymous user',
    'authenticated user',
    'administrator',
  );
}

/**
 * Define site permissions in code.
 *
 * Create a pinnakl module directory and place this function
 * in pinnakl.module.
 *
 * @param $role
 *   The role for which the permissions are being requested.
 *
 * @return
 *   An array defining all the permissions for the site.
 */
function pinnakl_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'access content',
      'view media',
    ),
    'authenticated user' => array(
      'access content',
      'view media',
    ),
    'administrator' => array(
      'access administration pages',
      'access all views',
      'access bean overview',
      'access content',
      'access content overview',
      'access contextual links',
      'access site in maintenance mode',
      'access site reports',
      'access toolbar',
      'access user profiles',
      'administer actions',
      'administer bean settings',
      'administer bean types',
      'administer beans',
      'administer blocks',
      'administer content types',
      'administer contexts',
      'administer features',
      'administer field collections',
      'administer fieldgroups',
      'administer filters',
      'administer image styles',
      'administer jscrollpane',
      'administer media',
      'administer menu',
      'administer modules',
      'administer nodes',
      'administer pathauto',
      'administer permissions',
      'administer redirects',
      'administer shortcuts',
      'administer site configuration',
      'administer software updates',
      'administer taxonomy',
      'administer themes',
      'administer url aliases',
      'administer users',
      'administer views',
      'block IP addresses',
      'bypass node access',
      'cancel account',
      'change own username',
      'create blog content',
      'create url aliases',
      'customize shortcut links',
      'delete any blog content',
      'delete own blog content',
      'delete revisions',
      'edit any blog content',
      'edit bean view mode',
      'edit media',
      'edit own blog content',
      'export secure permissions',
      'import media',
      'manage features',
      'notify of path changes',
      'revert revisions',
      'select account cancellation method',
      'switch shortcut sets',
      'view bean page',
      'view bean revisions',
      'view media',
      'view own unpublished content',
      'view revisions',
      'view the administration theme',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
